<?php

/**
 * mdApartamentoSearchTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class mdApartamentoSearchTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object mdApartamentoSearchTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('mdApartamentoSearch');
    }

		// deprecated: moved to mdApartamentoFindFormFilter.class.php::addMdPriceRangeColumnQuery
		static public function addPriceRangeQuery($query, $rango, $md_locacion_id, $fecha = array()){
			die('deprecated');
			if(!isset($fecha['from']) or $fecha['from']==''){
				$fecha = new DateTime();
			}else{
				$fecha = DateTime::createFromFormat('d/m/Y', $fecha['from']);
			}
			if(Doctrine::getTable('mdLocacion')->find($md_locacion_id)->esTemporadaAlta($fecha)){
				$field = 'precio_alta';
			}else{
				$field = 'precio_baja';
			}
			if(mdCurrencyHandler::getCurrent()->getId()!=1){
				$rango[0] = mdCurrencyConvertion::convert(mdCurrencyHandler::getCurrentCode(), 'EUR', $rango[0]);
				$rango[1] = mdCurrencyConvertion::convert(mdCurrencyHandler::getCurrentCode(), 'EUR', $rango[1]);
			}
			
			$query->addWhere($query->getRootAlias() . '.' . $field . ' between ' . $rango[0] . ' and ' . $rango[1]);

			return $query;
			
		}
		
}