<?php

/**
 * mdApartamento_mdComodidadTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class mdApartamento_mdComodidadTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object mdApartamento_mdComodidadTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('mdApartamento_mdComodidad');
    }
}