<?php

/**
 * mdDetalle
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    rentNchill
 * @subpackage model
 * @author     maui
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class mdDetalle extends BasemdDetalle
{
		public function  postSave($event) {
	    parent::postSave($event);

			$mdApartamentoSearch = Doctrine::getTable('mdApartamentoSearch')->find($this->getMdApartamentoId());
			if($mdApartamentoSearch){
				$mdApartamentoSearch->setMetraje($this->getMetraje());
				$mdApartamentoSearch->setCuartos($this->getCuartos());
				$mdApartamentoSearch->setTipoPropiedad($this->getTipoPropiedad());
                $mdApartamentoSearch->setMinimoDias($this->getMinimoDias());
				$mdApartamentoSearch->save();
			}
	}

}
