<?php

/**
 * mdDetalleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class mdDetalleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object mdDetalleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('mdDetalle');
    }
}