<?php

/**
 * mdLocacionTemporadaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class mdLocacionTemporadaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object mdLocacionTemporadaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('mdLocacionTemporada');
    }
}