<?php

/**
 * BasemdDetalle
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $md_apartamento_id
 * @property enum $tipo_propiedad
 * @property integer $cuartos
 * @property integer $banios
 * @property float $costo_extra
 * @property integer $minimo_dias
 * @property string $barrio
 * @property string $metraje
 * @property mdApartamento $mdApartamento
 * 
 * @method integer       getId()                Returns the current record's "id" value
 * @method integer       getMdApartamentoId()   Returns the current record's "md_apartamento_id" value
 * @method enum          getTipoPropiedad()     Returns the current record's "tipo_propiedad" value
 * @method integer       getCuartos()           Returns the current record's "cuartos" value
 * @method integer       getBanios()            Returns the current record's "banios" value
 * @method float         getCostoExtra()        Returns the current record's "costo_extra" value
 * @method integer       getMinimoDias()        Returns the current record's "minimo_dias" value
 * @method string        getBarrio()            Returns the current record's "barrio" value
 * @method string        getMetraje()           Returns the current record's "metraje" value
 * @method mdApartamento getMdApartamento()     Returns the current record's "mdApartamento" value
 * @method mdDetalle     setId()                Sets the current record's "id" value
 * @method mdDetalle     setMdApartamentoId()   Sets the current record's "md_apartamento_id" value
 * @method mdDetalle     setTipoPropiedad()     Sets the current record's "tipo_propiedad" value
 * @method mdDetalle     setCuartos()           Sets the current record's "cuartos" value
 * @method mdDetalle     setBanios()            Sets the current record's "banios" value
 * @method mdDetalle     setCostoExtra()        Sets the current record's "costo_extra" value
 * @method mdDetalle     setMinimoDias()        Sets the current record's "minimo_dias" value
 * @method mdDetalle     setBarrio()            Sets the current record's "barrio" value
 * @method mdDetalle     setMetraje()           Sets the current record's "metraje" value
 * @method mdDetalle     setMdApartamento()     Sets the current record's "mdApartamento" value
 * 
 * @package    rentNchill
 * @subpackage model
 * @author     maui
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasemdDetalle extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('md_detalle');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('md_apartamento_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('tipo_propiedad', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'apartment',
              1 => 'house',
              2 => 'bedNbreakfast',
              3 => 'cabin',
              4 => 'villa',
              5 => 'castle',
              6 => 'dorm',
              7 => 'treehouse',
              8 => 'boat',
              9 => 'automobile',
              10 => 'igloo',
             ),
             'notnull' => false,
             ));
        $this->hasColumn('cuartos', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => false,
             'length' => 4,
             ));
        $this->hasColumn('banios', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => false,
             'length' => 4,
             ));
        $this->hasColumn('costo_extra', 'float', null, array(
             'type' => 'float',
             'notnull' => false,
             'default' => 0,
             ));
        $this->hasColumn('minimo_dias', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => false,
             'default' => 1,
             'length' => 4,
             ));
        $this->hasColumn('barrio', 'string', 100, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 100,
             ));
        $this->hasColumn('metraje', 'string', 100, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('mdApartamento', array(
             'local' => 'md_apartamento_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}