<?php

/**
 * BasemdApartamento
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $md_locacion_id
 * @property boolean $activo
 * @property enum $tipo
 * @property integer $md_user_id
 * @property string $titulo
 * @property string $copete
 * @property string $descripcion
 * @property integer $md_currency_id
 * @property float $precio_alta
 * @property float $precio_media
 * @property float $precio_baja
 * @property integer $cantidad_personas
 * @property mdLocacion $mdLocacion
 * @property mdUser $mdUser
 * @property mdCurrency $mdCurrency
 * @property Doctrine_Collection $mdComodidad
 * @property Doctrine_Collection $mdOcupacion
 * @property Doctrine_Collection $mdDetalle
 * @property Doctrine_Collection $mdApartamentoSearch
 * @property Doctrine_Collection $mdReserva
 * 
 * @method integer             getId()                  Returns the current record's "id" value
 * @method integer             getMdLocacionId()        Returns the current record's "md_locacion_id" value
 * @method boolean             getActivo()              Returns the current record's "activo" value
 * @method enum                getTipo()                Returns the current record's "tipo" value
 * @method integer             getMdUserId()            Returns the current record's "md_user_id" value
 * @method string              getTitulo()              Returns the current record's "titulo" value
 * @method string              getCopete()              Returns the current record's "copete" value
 * @method string              getDescripcion()         Returns the current record's "descripcion" value
 * @method integer             getMdCurrencyId()        Returns the current record's "md_currency_id" value
 * @method float               getPrecioAlta()          Returns the current record's "precio_alta" value
 * @method float               getPrecioMedia()         Returns the current record's "precio_media" value
 * @method float               getPrecioBaja()          Returns the current record's "precio_baja" value
 * @method integer             getCantidadPersonas()    Returns the current record's "cantidad_personas" value
 * @method mdLocacion          getMdLocacion()          Returns the current record's "mdLocacion" value
 * @method mdUser              getMdUser()              Returns the current record's "mdUser" value
 * @method mdCurrency          getMdCurrency()          Returns the current record's "mdCurrency" value
 * @method Doctrine_Collection getMdComodidad()         Returns the current record's "mdComodidad" collection
 * @method Doctrine_Collection getMdOcupacion()         Returns the current record's "mdOcupacion" collection
 * @method Doctrine_Collection getMdDetalle()           Returns the current record's "mdDetalle" collection
 * @method Doctrine_Collection getMdApartamentoSearch() Returns the current record's "mdApartamentoSearch" collection
 * @method Doctrine_Collection getMdReserva()           Returns the current record's "mdReserva" collection
 * @method mdApartamento       setId()                  Sets the current record's "id" value
 * @method mdApartamento       setMdLocacionId()        Sets the current record's "md_locacion_id" value
 * @method mdApartamento       setActivo()              Sets the current record's "activo" value
 * @method mdApartamento       setTipo()                Sets the current record's "tipo" value
 * @method mdApartamento       setMdUserId()            Sets the current record's "md_user_id" value
 * @method mdApartamento       setTitulo()              Sets the current record's "titulo" value
 * @method mdApartamento       setCopete()              Sets the current record's "copete" value
 * @method mdApartamento       setDescripcion()         Sets the current record's "descripcion" value
 * @method mdApartamento       setMdCurrencyId()        Sets the current record's "md_currency_id" value
 * @method mdApartamento       setPrecioAlta()          Sets the current record's "precio_alta" value
 * @method mdApartamento       setPrecioMedia()         Sets the current record's "precio_media" value
 * @method mdApartamento       setPrecioBaja()          Sets the current record's "precio_baja" value
 * @method mdApartamento       setCantidadPersonas()    Sets the current record's "cantidad_personas" value
 * @method mdApartamento       setMdLocacion()          Sets the current record's "mdLocacion" value
 * @method mdApartamento       setMdUser()              Sets the current record's "mdUser" value
 * @method mdApartamento       setMdCurrency()          Sets the current record's "mdCurrency" value
 * @method mdApartamento       setMdComodidad()         Sets the current record's "mdComodidad" collection
 * @method mdApartamento       setMdOcupacion()         Sets the current record's "mdOcupacion" collection
 * @method mdApartamento       setMdDetalle()           Sets the current record's "mdDetalle" collection
 * @method mdApartamento       setMdApartamentoSearch() Sets the current record's "mdApartamentoSearch" collection
 * @method mdApartamento       setMdReserva()           Sets the current record's "mdReserva" collection
 * 
 * @package    rentNchill
 * @subpackage model
 * @author     maui
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasemdApartamento extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('md_apartamento');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('md_locacion_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('activo', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
        $this->hasColumn('tipo', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'comission',
              1 => 'fullservice',
             ),
             'notnull' => true,
             ));
        $this->hasColumn('md_user_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => false,
             'length' => 4,
             ));
        $this->hasColumn('titulo', 'string', 200, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 200,
             ));
        $this->hasColumn('copete', 'string', 300, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 300,
             ));
        $this->hasColumn('descripcion', 'string', 5000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 5000,
             ));
        $this->hasColumn('md_currency_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 1,
             'length' => 4,
             ));
        $this->hasColumn('precio_alta', 'float', null, array(
             'type' => 'float',
             'notnull' => true,
             ));
        $this->hasColumn('precio_media', 'float', null, array(
             'type' => 'float',
             'notnull' => true,
             ));
        $this->hasColumn('precio_baja', 'float', null, array(
             'type' => 'float',
             'notnull' => true,
             ));
        $this->hasColumn('cantidad_personas', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 2,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('mdLocacion', array(
             'local' => 'md_locacion_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('mdUser', array(
             'local' => 'md_user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('mdCurrency', array(
             'local' => 'md_currency_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('mdComodidad', array(
             'refClass' => 'mdApartamento_mdComodidad',
             'local' => 'md_apartamento_id',
             'foreign' => 'md_comodidad_id'));

        $this->hasMany('mdOcupacion', array(
             'local' => 'id',
             'foreign' => 'md_apartamento_id'));

        $this->hasMany('mdDetalle', array(
             'local' => 'id',
             'foreign' => 'md_apartamento_id'));

        $this->hasMany('mdApartamentoSearch', array(
             'local' => 'id',
             'foreign' => 'id'));

        $this->hasMany('mdReserva', array(
             'local' => 'id',
             'foreign' => 'md_apartamento_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $mdmediabehavior0 = new mdMediaBehavior();
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'titulo',
              1 => 'copete',
              2 => 'descripcion',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($mdmediabehavior0);
        $this->actAs($i18n0);
    }
}