<?php

/**
 * PluginmdGoogleMapTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginmdGoogleMapTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginmdGoogleMapTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginmdGoogleMap');
    }

    public function findByMultiples($keys = array(), $values = array()){
        $query = Doctrine_Query::create ()
                    ->select ('mdG.*')
                    ->from ('mdGoogleMap mdG');

        for ($i = 0; $i < count($keys); $i++){
            $query->addWhere('mdG.' . $keys[$i] . ' = ?', $values[$i]);
        }

        return $query->execute();
    }
}