<?php

/**
 * BasemdGenericSale
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $md_user_id
 * @property float $price
 * @property integer $status
 * @property integer $md_payment_id
 * @property mdUser $mdUser
 * @property mdGenericPayment $mdGenericPayment
 * @property Doctrine_Collection $mdGenericSaleItem
 * 
 * @method integer             getId()                Returns the current record's "id" value
 * @method integer             getMdUserId()          Returns the current record's "md_user_id" value
 * @method float               getPrice()             Returns the current record's "price" value
 * @method integer             getStatus()            Returns the current record's "status" value
 * @method integer             getMdPaymentId()       Returns the current record's "md_payment_id" value
 * @method mdUser              getMdUser()            Returns the current record's "mdUser" value
 * @method mdGenericPayment    getMdGenericPayment()  Returns the current record's "mdGenericPayment" value
 * @method Doctrine_Collection getMdGenericSaleItem() Returns the current record's "mdGenericSaleItem" collection
 * @method mdGenericSale       setId()                Sets the current record's "id" value
 * @method mdGenericSale       setMdUserId()          Sets the current record's "md_user_id" value
 * @method mdGenericSale       setPrice()             Sets the current record's "price" value
 * @method mdGenericSale       setStatus()            Sets the current record's "status" value
 * @method mdGenericSale       setMdPaymentId()       Sets the current record's "md_payment_id" value
 * @method mdGenericSale       setMdUser()            Sets the current record's "mdUser" value
 * @method mdGenericSale       setMdGenericPayment()  Sets the current record's "mdGenericPayment" value
 * @method mdGenericSale       setMdGenericSaleItem() Sets the current record's "mdGenericSaleItem" collection
 * 
 * @package    rentNchill
 * @subpackage model
 * @author     Rodrigo Santellan
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasemdGenericSale extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('md_generic_sale');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('md_user_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('price', 'float', 6, array(
             'type' => 'float',
             'notnull' => true,
             'unsigned' => true,
             'length' => 6,
             'scale' => '2',
             ));
        $this->hasColumn('status', 'integer', 4, array(
             'type' => 'integer',
             'default' => '0',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('md_payment_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('mdUser', array(
             'local' => 'md_user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('mdGenericPayment', array(
             'local' => 'md_payment_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('mdGenericSaleItem', array(
             'local' => 'id',
             'foreign' => 'md_generic_sale_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}