<?php

/**
 * BasemdGenericSaleItem
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $object_id
 * @property string $object_class
 * @property integer $md_generic_sale_id
 * @property mdGenericSale $mdGenericSale
 * 
 * @method integer           getId()                 Returns the current record's "id" value
 * @method integer           getObjectId()           Returns the current record's "object_id" value
 * @method string            getObjectClass()        Returns the current record's "object_class" value
 * @method integer           getMdGenericSaleId()    Returns the current record's "md_generic_sale_id" value
 * @method mdGenericSale     getMdGenericSale()      Returns the current record's "mdGenericSale" value
 * @method mdGenericSaleItem setId()                 Sets the current record's "id" value
 * @method mdGenericSaleItem setObjectId()           Sets the current record's "object_id" value
 * @method mdGenericSaleItem setObjectClass()        Sets the current record's "object_class" value
 * @method mdGenericSaleItem setMdGenericSaleId()    Sets the current record's "md_generic_sale_id" value
 * @method mdGenericSaleItem setMdGenericSale()      Sets the current record's "mdGenericSale" value
 * 
 * @package    rentNchill
 * @subpackage model
 * @author     maui
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasemdGenericSaleItem extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('md_generic_sale_item');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('object_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('object_class', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 128,
             ));
        $this->hasColumn('md_generic_sale_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('mdGenericSale', array(
             'local' => 'md_generic_sale_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}