<?php

/**
 * BasemdGenericPayment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $object_class
 * @property integer $object_id
 * @property Doctrine_Collection $mdGenericSale
 * 
 * @method integer             getId()            Returns the current record's "id" value
 * @method string              getObjectClass()   Returns the current record's "object_class" value
 * @method integer             getObjectId()      Returns the current record's "object_id" value
 * @method Doctrine_Collection getMdGenericSale() Returns the current record's "mdGenericSale" collection
 * @method mdGenericPayment    setId()            Sets the current record's "id" value
 * @method mdGenericPayment    setObjectClass()   Sets the current record's "object_class" value
 * @method mdGenericPayment    setObjectId()      Sets the current record's "object_id" value
 * @method mdGenericPayment    setMdGenericSale() Sets the current record's "mdGenericSale" collection
 * 
 * @package    rentNchill
 * @subpackage model
 * @author     maui
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasemdGenericPayment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('md_generic_payment');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('object_class', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 128,
             ));
        $this->hasColumn('object_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('mdGenericSale', array(
             'local' => 'id',
             'foreign' => 'md_payment_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}