INSERT INTO `md_comodidad_translation` (`id`, `nombre`, `lang`) VALUES 
('1', 'air conditioning', 'en'), 
('1', 'ar condicionado', 'pt'), 
('2', 'Suitable for families', 'en'), 
('2', 'Adequado para famílias', 'pt'), 
('3', 'cable', 'en'), 
('3', 'TV a cabo', 'pt'), 
('4', 'heating', 'en'), 
('4', 'Aquecimento', 'pt'), 
('5', 'fireplace', 'en'), 
('5', 'lareira', 'pt'), 
('6', 'kitchen', 'en'), 
('6', 'cozinha', 'pt'), 
('7', 'breakfast', 'en'), 
('7', 'café da manhã', 'pt'), 
('8', 'disabled', 'en'), 
('8', 'desativado', 'pt'), 
('9', 'events', 'en'), 
('9', 'eventos', 'pt'), 
('10', 'smokers', 'en'), 
('10', 'fumadores', 'pt'), 
('11', 'Garage', 'en'), 
('11', 'garagem', 'pt'), 
('12', 'gym', 'en'), 
('12', 'ginásio', 'pt'), 
('13', 'Internet', 'en'), 
('13', 'Internet', 'pt'), 
('14', 'Jacuzzi', 'en'), 
('14', 'Jacuzzi', 'pt'), 
('15', 'washing machine', 'en'), 
('15', 'máquina de lavar', 'pt'), 
('16', 'Pets', 'en'), 
('16', 'Animais de estimação', 'pt'), 
('17', 'pool', 'en'), 
('17', 'Piscina', 'pt'), 
('18', 'porter', 'en'), 
('18', 'porteiro', 'pt'), 
('19', 'TV', 'en'), 
('19', 'TV', 'pt'), 
('20', 'WiFi', 'en'), 
('20', 'WiFi', 'pt');
