generator:
  class: sfDoctrineGenerator
  param:
    model_class:           mdComodidad
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          md_comodidad
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        display:    [nombre]
      filter:  
        class: false
      form:    ~
      edit:    ~
      new:     ~
