<?php

/**
 * mdApartamentoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class mdApartamentoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object mdApartamentoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('mdApartamento');
    }

		/**
		 * retorna los apartamentos reservados de ahora en adelante por un usuario
		 *
		 * @return sfDoctrineCollection
		 * @author maui .-
		 **/
		public function findReservedBy($md_user_id)
		{
			$q = $this->createQuery('a');
			$q->innerJoin('a.mdReserva r')
			->addWhere('r.md_user_id=?', $md_user_id)
			->addWhere('r.fecha_desde > ?', date('Y-m-d'));
			return $q->execute();
		}

		/**
		 * retorna los apartamentos visitados por un usuario
		 *
		 * @return sfDoctrineCollection
		 * @author maui .-
		 **/
		public function findVisitedBy($md_user_id)
		{
			$q = $this->createQuery('a');
			$q->innerJoin('a.mdReserva r')
			->addWhere('r.md_user_id=?', $md_user_id)
			->addWhere('r.fecha_desde <= ?', date('Y-m-d'));
			return $q->execute();
		}

}