<?php

/**
 * mdComodidadTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class mdComodidadTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object mdComodidadTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('mdComodidad');
    }
}