<?php

/**
 * mdOcupacionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class mdOcupacionTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object mdOcupacionTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('mdOcupacion');
    }

    /**
     * borra todas las ocupaciones para un id de apartamento
     *
     * @return $this
     * @author maui .-
     * */
    public function deleteByMdApartamentoId($id) {
        $objetos = $this->findBymd_apartamento_id($id);
        foreach ($objetos as $objeto)
            $objeto->delete();

        return $this;
    }

    /**
     * retorna el contenido del input para el widget datepicker para un apartamento
     *
     * @return void
     * @author maui .-
     * */
    public function getWidgetContentForId($id) {

        $objetos = $this->findBymd_apartamento_id($id);
        $salida = array();
        foreach ($objetos as $objeto) {
            $salida[] = $objeto->getDateTimeObject('fecha')->format('Y-m-d');
        }
        return implode(',', $salida);
    }
    
    public function getDiasOcupados($apartamento, $start, $end)
    {
      $sql = "SELECT count( * ) AS suma FROM `md_ocupacion` WHERE `md_apartamento_id` =? AND `fecha` >= ? AND `fecha` <= ? ";
      $conn = Doctrine_Manager::getInstance()->getCurrentConnection(); 
      //$r = $conn->fetchAssoc($sql, array($apartamento, $start, $end));
      $r = $conn->fetchOne($sql, array($apartamento, $start, $end));
      
      return $r;
    }

}