<?php

/**
 * mdReserva
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    rentNchill
 * @subpackage model
 * @author     maui
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class mdReserva extends BasemdReserva
{
  const PENDING = 'pending';
  const CONFIRM = 'confirm';
  const EFECTIVE = 'efective';
  const CANCEL = 'cancel';
  const CANCELPAYPAL = 'cancelPayPal';
  const ERRORPAYPAL = 'errorPayPal';
  const PREPAYPAL = 'prePayPal';
  
  public function getUser()
  {
    return $this->getMdUser();
  }
  
  public function getApartamento()
  {
    return $this->getMdApartamento();
  }
  
  public function getDesde()
  {
    return format_date($this->getFechaDesde(), 'D');
  }
  
  public function getHasta()
  {
    return format_date($this->getFechaHasta(), 'D');
  }
  
  public function getMoneda()
  {
    return $this->getMdCurrency();
  }
  
  public function getTotalRedondeado()
  {
    return round($this->getTotal(), 0);
  }
  
  public function getLugar()
  {
    return $this->getMdApartamento()->getMdLocacion();
  }
}
