<?php

/**
 * mdReservaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class mdReservaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object mdReservaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('mdReserva');
    }
    
    public function retrieveOnlyNew(Doctrine_Query $q)
    {
      $rootAlias = $q->getRootAlias();
      $q->addWhere($rootAlias.".fecha_hasta >= NOW()");
      return $q;
    }
    
    public function statusEstadistic()
    {
      $conn = Doctrine_Manager::getInstance()->getCurrentConnection(); 
      $sql = "SELECT count(*) as cantidad, status FROM md_reserva m group by status";
      $r = $conn->fetchAssoc($sql, array());
      return $r;
    }
    
    public function currencyEstadistic()
    {
      $conn = Doctrine_Manager::getInstance()->getCurrentConnection(); 
      $sql = "SELECT count(*) as cantidad, md_currency_id FROM md_reserva m group by md_currency_id";
      $r = $conn->fetchAssoc($sql, array());
      return $r;
    }
    
    public function locationEstadistic()
    {
      $conn = Doctrine_Manager::getInstance()->getCurrentConnection(); 
      $sql = "SELECT count(a.id) as cantidad, a.md_locacion_id FROM md_reserva m, md_apartamento a where m.md_apartamento_id = a.id group by a.md_locacion_id";
      $r = $conn->fetchAssoc($sql, array());
      return $r;
    }
    
    public function createdAtEstadistic()
    {
      $conn = Doctrine_Manager::getInstance()->getCurrentConnection(); 
      $sql = "SELECT count(id) as cantidad, MONTH(created_at) as mes FROM md_reserva group by MONTH(created_at) order by mes";
      $r = $conn->fetchAssoc($sql, array());
      return $r;
    }
    
    public function fromDateEstadistic()
    {
      $conn = Doctrine_Manager::getInstance()->getCurrentConnection(); 
      $sql = "SELECT count(id) as cantidad, MONTH(fecha_desde) as mes FROM md_reserva group by MONTH(fecha_desde) order by mes";
      $r = $conn->fetchAssoc($sql, array());
      return $r;
    }
    
    public function retrieveUsersWithEspecifications($status = "pending")
    {
      $sql = "select count(m.id) as suma, m.status, m.md_user_id, u.email, u.culture, p.username, up.name, up.last_name, up.country_code from md_user u, md_content c, md_user_profile up, md_passport p, md_reserva m where c.object_class = 'mdUserProfile' and c.md_user_id = u.id and c.object_id = up.id and u.id = p.md_user_id and m.md_user_id = u.id and m.status = ? group by m.md_user_id order by suma desc";
      $conn = Doctrine_Manager::getInstance()->getCurrentConnection();
      $r = $conn->fetchAssoc($sql, array($status));
      return $r;
    }
}