<?php

/**
 * BasemdDisponibilidad
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $md_apartamento_id
 * @property timestamp $fecha_desde
 * @property timestamp $fecha_hasta
 * @property mdApartamento $mdApartamento
 * 
 * @method integer          getId()                Returns the current record's "id" value
 * @method integer          getMdApartamentoId()   Returns the current record's "md_apartamento_id" value
 * @method timestamp        getFechaDesde()        Returns the current record's "fecha_desde" value
 * @method timestamp        getFechaHasta()        Returns the current record's "fecha_hasta" value
 * @method mdApartamento    getMdApartamento()     Returns the current record's "mdApartamento" value
 * @method mdDisponibilidad setId()                Sets the current record's "id" value
 * @method mdDisponibilidad setMdApartamentoId()   Sets the current record's "md_apartamento_id" value
 * @method mdDisponibilidad setFechaDesde()        Sets the current record's "fecha_desde" value
 * @method mdDisponibilidad setFechaHasta()        Sets the current record's "fecha_hasta" value
 * @method mdDisponibilidad setMdApartamento()     Sets the current record's "mdApartamento" value
 * 
 * @package    rentNchill
 * @subpackage model
 * @author     maui
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasemdDisponibilidad extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('md_disponibilidad');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('md_apartamento_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('fecha_desde', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('fecha_hasta', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('mdApartamento', array(
             'local' => 'md_apartamento_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}