<?php

/**
 * BasemdApartamento_mdComodidad
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $md_apartamento_id
 * @property integer $md_comodidad_id
 * @property mdApartamento $mdApartamento
 * @property mdComodidad $mdComodidad
 * 
 * @method integer                   getMdApartamentoId()   Returns the current record's "md_apartamento_id" value
 * @method integer                   getMdComodidadId()     Returns the current record's "md_comodidad_id" value
 * @method mdApartamento             getMdApartamento()     Returns the current record's "mdApartamento" value
 * @method mdComodidad               getMdComodidad()       Returns the current record's "mdComodidad" value
 * @method mdApartamento_mdComodidad setMdApartamentoId()   Sets the current record's "md_apartamento_id" value
 * @method mdApartamento_mdComodidad setMdComodidadId()     Sets the current record's "md_comodidad_id" value
 * @method mdApartamento_mdComodidad setMdApartamento()     Sets the current record's "mdApartamento" value
 * @method mdApartamento_mdComodidad setMdComodidad()       Sets the current record's "mdComodidad" value
 * 
 * @package    rentNchill
 * @subpackage model
 * @author     maui
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasemdApartamento_mdComodidad extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('md_apartamento_md_comodidad');
        $this->hasColumn('md_apartamento_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('md_comodidad_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('mdApartamento', array(
             'local' => 'md_apartamento_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('mdComodidad', array(
             'local' => 'md_comodidad_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}