<?php

/**
 * PluginmdNewsletterSendTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginmdNewsletterSendTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginmdNewsletterSendTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginmdNewsletterSend');
    }
}