<?php

/**
 * PluginmdNewsLetterGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginmdNewsLetterGroup extends BasemdNewsLetterGroup
{

	/**
	 * relaciona un usuario con el grupo
	 *
	 * @return mdNewsletterGroup
	 * @author maui .-
	 **/
	public function addUser($mdNewsletterUser)
	{
		$coll = Doctrine::getTable('mdNewsLetterGroupUser')->findOneByMdNewsletterUserIdAndMdNewsletterGroupId($mdNewsletterUser->getId(),$this->getId());
		if(!$coll or $coll->count() == 0){
			$groupUser = new mdNewsLetterGroupUser();
			$groupUser->setMdNewsletterGroupId($this->getId())->setMdNewsletterUserId($mdNewsletterUser->getId());
			$groupUser->save();
			return $this;
		}
		return false;
	}

}