<?php

/**
 * PluginmdNewsletterContentSendedTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginmdNewsletterContentSendedTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginmdNewsletterContentSendedTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginmdNewsletterContentSended');
    }
    
    public function retrieveNotSended()
    {
      $query = $this->createQuery("mdNLCS")
            ->addWhere("mdNLCS.sended = ?", false)
            ->addWhere("mdNLCS.sending_date <= ?", date('Y-m-d H:i:s',time()));
      return $query->execute();
    }
    
    public function retrieveAllMdNewsletterContentSendedOfId($id)
    {
      $query = $this->createQuery("mdNLCS")
            ->addWhere("mdNLCS.md_newsletter_content_id = ?", $id)
            ->orderBy("mdNLCS.created_at DESC");
      return $query->execute();
    }
        
}
