all:
  mailer:
    class: sfMailer
    param:
      logging:           %SF_LOGGING_ENABLED%
      charset:           %SF_CHARSET%
      transport:
        class: Swift_MailTransport
        param:
          host:       localhost
          port:       25

