<?php

/**
 * mdGenericSaleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class mdGenericSaleTable extends PluginmdGenericSaleTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object mdGenericSaleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('mdGenericSale');
    }
}