<?php

/**
 * mdGenericSaleItemTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class mdGenericSaleItemTable extends PluginmdGenericSaleItemTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object mdGenericSaleItemTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('mdGenericSaleItem');
    }
}