<?php

/**
 * mdGenericPaymentPaypalTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class mdGenericPaymentPaypalTable extends PluginmdGenericPaymentPaypalTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object mdGenericPaymentPaypalTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('mdGenericPaymentPaypal');
    }
}