<?php

/**
 * mdGenericPaymentWestern
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    rentNchill
 * @subpackage model
 * @author     maui
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class mdGenericPaymentWestern extends PluginmdGenericPaymentWestern
{
}
