<?php

/**
 * PluginmdGenericPaymentWesternTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginmdGenericPaymentWesternTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginmdGenericPaymentWesternTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginmdGenericPaymentWestern');
    }
}