<?php

/**
 * PluginmdGenericPaymentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginmdGenericPaymentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginmdGenericPaymentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginmdGenericPayment');
    }
}