<?php

/**
 * PluginmdGenericSaleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginmdGenericSaleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginmdGenericSaleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginmdGenericSale');
    }
    
    /**
     * Devuelve el ultimo pago realizado por el objeto $object
     *  
     * @param mdContentConcrete $object
     * @return mdGenericSale
     */
    public function getGenericSale($object)
    {
        $q = Doctrine_Query::create()
          ->select('mdG.*')
          ->from('mdGenericSale mdG')
          ->innerJoin('mdG.mdGenericSaleItem mdI')
          ->where('mdI.object_class = ?', $object->getObjectClass())
          ->addWhere('mdI.object_id = ?', $object->getId())
          ->orderBy('mdG.id DESC')
          ->limit(1);

        return $q->fetchOne();
    }
}