<?php

/**
 * PluginmdGenericPaymentOtherTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginmdGenericPaymentOtherTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginmdGenericPaymentOtherTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginmdGenericPaymentOther');
    }
}