<?php

/**
 * PluginmdGenericSaleItemTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginmdGenericSaleItemTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginmdGenericSaleItemTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginmdGenericSaleItem');
    }
}