<?php

/**
 * BasemdGenericPaymentGiroBancario
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $note
 * 
 * @method integer                      getId()   Returns the current record's "id" value
 * @method string                       getNote() Returns the current record's "note" value
 * @method mdGenericPaymentGiroBancario setId()   Sets the current record's "id" value
 * @method mdGenericPaymentGiroBancario setNote() Sets the current record's "note" value
 * 
 * @package    rentNchill
 * @subpackage model
 * @author     Rodrigo Santellan
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasemdGenericPaymentGiroBancario extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('md_generic_payment_giro_bancario');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('note', 'string', 128, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 128,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}