<?php

/**
 * mdGoogleMapTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class mdGoogleMapTable extends PluginmdGoogleMapTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object mdGoogleMapTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('mdGoogleMap');
    }
}