<?php

/**
 * mdGenericPaymentAbitabTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class mdGenericPaymentAbitabTable extends PluginmdGenericPaymentAbitabTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object mdGenericPaymentAbitabTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('mdGenericPaymentAbitab');
    }
}