<?php

/**
 * PluginmdGenericSaleItem
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginmdGenericSaleItem extends BasemdGenericSaleItem
{
	public function getObject(){
		return Doctrine::getTable($this->getObjectClass())->find($this->getObjectId());
	}
}