<?php

/**
 * PluginmdGenericPaymentPaypalTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginmdGenericPaymentPaypalTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginmdGenericPaymentPaypalTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginmdGenericPaymentPaypal');
    }
}