<?php

/**
 * BasemdGenericPaymentOther
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $note
 * 
 * @method integer               getId()   Returns the current record's "id" value
 * @method string                getNote() Returns the current record's "note" value
 * @method mdGenericPaymentOther setId()   Sets the current record's "id" value
 * @method mdGenericPaymentOther setNote() Sets the current record's "note" value
 * 
 * @package    rentNchill
 * @subpackage model
 * @author     maui
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasemdGenericPaymentOther extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('md_generic_payment_other');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('note', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 128,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}