<?php

/**
 * mdDisponibilidadTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class mdDisponibilidadTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object mdDisponibilidadTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('mdDisponibilidad');
    }
}