<?php

/**
 * mdLocacionTemporada
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    rentNchill
 * @subpackage model
 * @author     maui
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class mdLocacionTemporada extends BasemdLocacionTemporada
{

	public function getDesde(){
      return format_date($this->getDateFrom(), 'D');
      
	}

	public function getHasta(){
      return format_date($this->getDateTo(), 'D');
	}
}
