<?php

/**
 * mdLocacionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class mdLocacionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object mdLocacionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('mdLocacion');
    }
}