<?php

/**
 * mdReservaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class mdReservaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object mdReservaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('mdReserva');
    }
    
    public function retrieveOnlyNew(Doctrine_Query $q)
    {
      $rootAlias = $q->getRootAlias();
      $q->addWhere($rootAlias.".fecha_hasta >= NOW()");
      return $q;
    }
}