<?php

/**
 * temporadaAnualTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class temporadaAnualTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object temporadaAnualTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('temporadaAnual');
    }
	
	public function retrieveByDatesAndLocation($location_id, $date_from, $date_to)
	{
	  $query = $this->createQuery('tempAnual')
			  ->where('tempAnual.md_locacion_id = ?', $location_id)
			  ->addWhere('fecha >= ?', $date_from)
			  ->addWhere('fecha <= ?', $date_to);
	  return $query->execute();
				
	}
}