<?php

/**
 * PluginmdGenericPaymentAbitabTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginmdGenericPaymentAbitabTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginmdGenericPaymentAbitabTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginmdGenericPaymentAbitab');
    }
}