<?php

/**
 * PluginmdGenericPaymentGiroBancarioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginmdGenericPaymentGiroBancarioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginmdGenericPaymentGiroBancarioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginmdGenericPaymentGiroBancario');
    }
}