<?php

/**
 * mdGenericPaymentGiroBancarioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class mdGenericPaymentGiroBancarioTable extends PluginmdGenericPaymentGiroBancarioTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object mdGenericPaymentGiroBancarioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('mdGenericPaymentGiroBancario');
    }
}