<?php

/**
 * mdGenericPaymentOtherTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class mdGenericPaymentOtherTable extends PluginmdGenericPaymentOtherTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object mdGenericPaymentOtherTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('mdGenericPaymentOther');
    }
}