<?php

/**
 * mdGenericPaymentWesternTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class mdGenericPaymentWesternTable extends PluginmdGenericPaymentWesternTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object mdGenericPaymentWesternTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('mdGenericPaymentWestern');
    }
}